#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

autoload -Uz promptinit
promptinit
prompt minimal

export PATH="$HOME/.yarn/bin:$PATH"

# add custom completion scripts
fpath=(~/.zprezto/external/salesforce-cli-zsh-completion $fpath)

# compsys initialization
autoload -U compinit
compinit
